services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_rahasia
      POSTGRES_DB: ssd_inspection
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://admin:password_rahasia@db:5432/ssd_inspection?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3001
      FRONTEND_URL: http://frontend/render.html
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: ["npm", "run", "worker"]
    environment:
      DATABASE_URL: postgres://admin:password_rahasia@db:5432/ssd_inspection?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONTEND_URL: http://frontend/render.html
    depends_on:
      - db
      - redis
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
